### ISSUE TITLE
npm install Cannot find module '../src/app/store/createDevStore

### ISSUE THREAD

**Issue by AveVlad** [zalmoxisus/remotedev-app#18]
last commit:

```console
commit 04337c6e7476f54d19bd5c6725420787d89f13ed
Author: Zalmoxisus <zalmoxisus@gmail.com>
Date:   Fri Sep 16 12:07:01 2016 +0300

    Remove React Router till v4
```

log
```console
~/Projects/remotedev-app on  master ⌚ 17:32:15
$ npm i
npm WARN deprecated electron-packager@5.2.1: Critical security bug fixed in v7.0.0 - read more at https://github.com/electron-userland/electron-packager/issues/333
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated minimatch@2.0.4: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global appdmg@0.3.10 should be installed with -g

> macos-alias@0.2.9 install /Users/name/Projects/remotedev-app/node_modules/macos-alias
> node-gyp rebuild

  CXX(target) Release/obj.target/volume/src/volume.o
  SOLINK_MODULE(target) Release/volume.node

> fsevents@1.0.14 install /Users/name/Projects/remotedev-app/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/name/Projects/remotedev-app/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fs-xattr@0.1.14 install /Users/name/Projects/remotedev-app/node_modules/fs-xattr
> node-gyp rebuild

  CXX(target) Release/obj.target/xattr/src/async.o
  CXX(target) Release/obj.target/xattr/src/error.o
  CXX(target) Release/obj.target/xattr/src/sync.o
  CXX(target) Release/obj.target/xattr/src/util.o
  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/xattr.node

> chromedriver@2.24.1 install /Users/name/Projects/remotedev-app/node_modules/chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.24/chromedriver_mac64.zip
Saving to /var/folders/n3/4m0c5s1s5b93mp670k2l6rq80000gn/T/chromedriver/chromedriver_mac64.zip
Receiving...
Received 783K...
Received 1577K...
Received 2360K...
Received 3149K...
Received 3944K...
Received 4484K total.
Extracting zip contents
Copying to target path /Users/name/Projects/remotedev-app/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /Users/name/Projects/remotedev-app/node_modules/chromedriver/lib/chromedriver/chromedriver

> electron-prebuilt@0.36.12 postinstall /Users/name/Projects/remotedev-app/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.36.12-darwin-x64.zip
[============================================>] 100.0% of 40.52 MB (527.9 kB/s)

> remotedev-app@0.7.0 prepublish /Users/name/Projects/remotedev-app
> eslint ./src/app && npm run test && npm run build && npm run build:umd && npm run build:umd:min


> remotedev-app@0.7.0 test /Users/name/Projects/remotedev-app
> BABEL_ENV=test mocha --require test/setup.js --recursive test

module.js:341
    throw err;
    ^

Error: Cannot find module '../src/app/store/createDevStore'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/name/Projects/remotedev-app/test/index.spec.js:4:1)
    at Module._compile (module.js:413:34)
    at loader (/Users/name/Projects/remotedev-app/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/name/Projects/remotedev-app/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /Users/name/Projects/remotedev-app/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/name/Projects/remotedev-app/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/name/Projects/remotedev-app/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/name/Projects/remotedev-app/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node5/5.12.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! remotedev-app@0.7.0 test: `BABEL_ENV=test mocha --require test/setup.js --recursive test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remotedev-app@0.7.0 test script 'BABEL_ENV=test mocha --require test/setup.js --recursive test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the remotedev-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     BABEL_ENV=test mocha --require test/setup.js --recursive test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs remotedev-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls remotedev-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/name/Projects/remotedev-app/npm-debug.log

npm WARN redux-devtools-chart-monitor@1.4.2 requires a peer of redux-devtools@^3.0.0 but none was installed.
npm WARN redux-devtools-log-monitor@1.0.11 requires a peer of redux-devtools@^3.0.0 but none was installed.
npm WARN redux-slider-monitor@1.0.7 requires a peer of redux-devtools@^3.0.0 but none was installed.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node5/5.12.0/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! remotedev-app@0.7.0 prepublish: `eslint ./src/app && npm run test && npm run build && npm run build:umd && npm run build:umd:min`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remotedev-app@0.7.0 prepublish script 'eslint ./src/app && npm run test && npm run build && npm run build:umd && npm run build:umd:min'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the remotedev-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint ./src/app && npm run test && npm run build && npm run build:umd && npm run build:umd:min
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs remotedev-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls remotedev-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/name/Projects/remotedev-app/npm-debug.log
```

**Comment by AveVlad** [comment]
sorry, I forgot that master branch is not required to be stable

**Comment by zalmoxisus** [comment]
@AveVlad, thanks for the report. Yes, I forgot to remove this unused import in tests. Fixed.

**Comment by AveVlad** [comment]
thanks)
